# Generated by Django 4.2.1 on 2023-05-12 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speaker', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Speker',
            new_name='Speaker',
        ),
    ]
