# Generated by Django 4.2.1 on 2023-05-10 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_alter_feedback_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.CharField(choices=[('Bad', '😞'), ('Poor', '🙁'), ('Average', '😐'), ('Good', '🙂'), ('Excellent', '😀')], max_length=100),
        ),
    ]
