# Generated by Django 4.2.1 on 2023-05-13 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_feedback_speaker_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='user',
            new_name='rater',
        ),
    ]
