# Generated by Django 4.2.1 on 2023-05-14 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainingtitle', '0001_initial'),
        ('feedback', '0009_alter_feedback_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='trainingtitle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='trainingtitle.trainingtitle'),
        ),
    ]
