# Generated by Django 4.2.1 on 2023-05-14 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('speaker', '0002_rename_speker_speaker'),
        ('trainingtitle', '0002_trainingtitle_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingtitle',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='speaker.speaker'),
        ),
    ]
