# Generated by Django 4.2.1 on 2023-05-14 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainingtitle', '0003_alter_trainingtitle_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingtitle',
            old_name='user',
            new_name='speaker',
        ),
    ]
